version: 2
jobs:
  build:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: echo "Checked out, ready to install dependencies."
      - run: npm install
      - run: mkdir -p my_workspace
      - run: apk add ca-certificates
      - run: echo "Dependencies installed successfully." > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  test:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: npm install -g testengine-cli
      - run: testengine -u circleci -p circlecitest jobs report output=./reports format=junit da4395ff-6238-4f0f-91ef-ab8c52788281
      - store_artifacts:
          path: ./reports
      - run: ls ./reports
      - store_test_results: 
          path: ./reports/output.xml
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - test:
          requires:
            - build